### ISSUE TITLE
use of the word model/state

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/learn-elm-architecture-in-javascript#11]
Hi Nelson, Just wanted to raise a question on here. 

Why call the argument in the _update_ function **model** and then when calling the function have it defined as the **state**, could we just not call it **model** when calling it? 

It is a minor thing but it may bamboozle a few beginner or am I being too cautious? what are your thoughts? 

<img width="710" alt="screen shot 2017-05-09 at 12 26 42" src="https://cloud.githubusercontent.com/assets/2305591/25848674/4fbe38d4-34b3-11e7-80cf-1eca5ac4082d.png">

**Comment by sohilpandya** [comment]
Actually, halfway through this, I am unsure if this is even an issue. Just got a little too carried away. Will close and can be there for reference. 👍

**Comment by nelsonic** [comment]
@sohilpandya yeah, I think that is a **100% Valid/Legit Question**! ❓ 
Why call it `state` in one place and `model` in the other? 🤔 
This _could_ easily be _confusing_ to beginners... 😞

**Comment by nelsonic** [comment]
@sohilpandya I _think_ I've replaced all instances of the word state in the code and docs.
please take another look tomorrow and confirm it's clearererer. thanks! 👍

**Comment by sohilpandya** [comment]
Thanks @nelsonic! I'll definitely look into it. ❤️
