### ISSUE TITLE
"Local copy" confusion

### ISSUE THREAD

**Issue by rjmk** [dwyl/learn-elm-architecture-in-javascript#14]
[This comment](https://github.com/dwyl/learn-elm-architecture-in-javascript/blob/d5b762e3f6459c9693945c9830cb13cf8d7d999b/examples/counter-basic/index.html#L51) reads "make local copies of the init parameters", but I believe that this is inaccurate. 

In the codebase as written, I think it makes a local copy of `model`, but not `update` or `view`. The function probably shouldn't know that `model` will be pass-by-value anyway, and so should consider the possiblity it's not making a copy of any of those values.

**Comment by nelsonic** [comment]
@rjmk what if we re-write the `mount` function signature to accept 4 arguments: 
`mount(model, update, view, root_element_id)`
then not bother assigning these to new variables inside the `mount` function?
Given that they are _references_ in any case would this be _simpler_ to a beginner?

**Comment by rjmk** [comment]
I would probably take the four arguments or just refer to `muv.{model, update, view}` in the body of the function. I don't know which is preferable
