### ISSUE TITLE
Abstract superlatives

### ISSUE THREAD

**Issue by rjmk** [dwyl/learn-elm-architecture-in-javascript#16]
Mileage may vary, but I find language like

> Anyone who knows a little bit of JavaScript and wants to learn how to organize/structure 
their code/app in the most sane, predictable and testable way.

(from [here](https://github.com/dwyl/learn-elm-architecture-in-javascript/tree/d5b762e3f6459c9693945c9830cb13cf8d7d999b#who-should-i-readlearn-this)) quite off-putting.

It's hard to provide evidence for things like "most sane", and anyway, the most sane way to organise something probably depends on the specifics of the thing you're trying to organise. There are definitely tonnes of advantages to the Elm Architecture, but I'm not sure it's the "most" anything.

Also, as a user, I would probably stop reading at this point because it looks quite dogmatic.

**Comment by nelsonic** [comment]
@rjmk thank you _so_ much for the level-headed feedback! ❤️ 
How would you propose re-writing the intro in a _less_ "_dogmatic_" (_good description BTW_!) way?

**Comment by rjmk** [comment]
I think removing "most" is sufficient. In my opinion, it's fine to make a recommendation and not everyone has time to learn several alternatives
