### ISSUE TITLE
typo on the cloning project command

### ISSUE THREAD

**Issue by SimonLab** [dwyl/learn-elm-architecture-in-javascript#17]
On the [clone-this-repository](https://github.com/dwyl/learn-elm-architecture-in-javascript#1-clone-this-repository) section

```git clone https://github.com/dwyl/learn-elm-architecture-in-javascript.git && learn-elm-architecture-in-javascript``` 
should be (adding change directory command```cd``` ):

```git clone https://github.com/dwyl/learn-elm-architecture-in-javascript.git && cd learn-elm-architecture-in-javascript```

**Comment by nelsonic** [comment]
@SimonLab well-spotted! if you have time to fix/PR please do. thanks! 👍

**Comment by SimonLab** [comment]
fixed with #18
