### ISSUE TITLE
Unclear sections in the TDD portion 

### ISSUE THREAD

**Issue by finnhodgkin** [dwyl/learn-elm-architecture-in-javascript#30]
In section 9.1 the workshop suggests the reset action be named 'res', but then for the rest of the text lists it as 'reset'. There's a premade 'reset' css class so it definitely makes more sense to just keep it as 'reset' the whole way through.

> ![Test instructions](https://user-images.githubusercontent.com/22300773/27010893-3eb77132-4ea7-11e7-85da-4df98c76fc54.png)

Then in sections 9.4 and 9.5 when writing tests for the reset button UI, the expected behaviour is for the two newly written tests to fail, but what actually happens is test number 5 fails too:

> ![Failing test #5](https://user-images.githubusercontent.com/22300773/27010905-a2e8ad60-4ea7-11e7-92ba-73d6f265e1ab.png)
 
Although sorting the test is an easy fix, it's not mentioned in the text so could easily be misconstrued by beginners as being due to them messing something else up.

Happy to make a quick PR if you want.

**Comment by nelsonic** [comment]
@finnhodgkin thanks for reporting this issue. this is indeed unclear (_confusing_!) if you have time, please fix in PR! 👍

**Comment by finnhodgkin** [comment]
I also changed the suggested UI tests in section 9.4 - there was an incorrect call to mount (passing in an options object instead of plain arguments) and the final test didn't `clear` the test counter.

**Comment by nelsonic** [comment]
@finnhodgkin thanks again! 🎉
