### ISSUE TITLE
Gif on line 169 of README needs updating

### ISSUE THREAD

**Issue by iteles** [dwyl/learn-elm-architecture-in-javascript#62]
The `gif` on line https://github.com/dwyl/learn-elm-architecture-in-javascript/blame/master/README.md#L169 of the README needs to be updated to remove `model` and replace this with _just_ the initial value.
<img width="690" alt="0-without-model-for-initial-value" src="https://user-images.githubusercontent.com/4185328/44005364-ffe6ab44-9e69-11e8-91da-18ad67e9aaf6.png">

Having the word `model` there means the app doesn't work.

@nelsonic Which gif-making app do you recommend for the change?

**Comment by nelsonic** [comment]
@iteles I didn't use a gif-making-app at all. just took screenshots or videos 
and uploaded to http://gifmaker.me

But I'm _considering_ using Scrimba to re-do the tutorial so people can follow along more interactively.

**Comment by iteles** [comment]
In the meantime, updating this gif (this isn't amazing, but this was my 3rd try, I don't know how you made the original so perfect!):

![elm-architecture-counter-mount-update](https://user-images.githubusercontent.com/4185328/46260332-6f107980-c4dc-11e8-98c8-e1775453dfac.gif)

**Comment by nelsonic** [comment]
@iteles did you make a PR with the updated GiF? (_are you able to check how **big** the file is?_)

**Comment by iteles** [comment]
I haven't made the PR yet but the gif was 37kb on my computer!

**Comment by nelsonic** [comment]
37Kb is good. ship it! :shipit:
